[package]
name = "neovide"
version = "0.6.0"
authors = ["keith <keith@the-simmons.net>"]
edition = "2018"
build = "build.rs"
description = "A simple GUI for Neovim."

[features]
default = ["sdl2"]
embed-fonts = []
sdl2 = ["skulpin/skulpin_sdl2"]
winit = ["skulpin/skulpin_winit"]

[dependencies]
euclid = "0.20.7"
font-kit = "0.6.0"
skribo = { git = "https://github.com/linebender/skribo" }
lru = "0.4.3"
skulpin = { git = "https://github.com/uhuntu/skulpin", branch = "hunt2" }
derive-new = "0.5"
rmpv = "0.4.4"
rust-embed = { version = "5.2.0", features = ["debug-embed"] }
image = "0.22.3"
nvim-rs = { git = "https://github.com/kethku/nvim-rs", features = [ "use_tokio" ] }
tokio = { version = "0.2.9", features = [ "blocking", "process", "time" ] }
async-trait = "0.1.18"
lazy_static = "1.4.0"
unicode-segmentation = "1.6.0"
log = "0.4.8"
flexi_logger = { version = "0.14.6", default-features = false }
anyhow = "1.0.26"
parking_lot="0.10.0"
cfg-if = "0.1.10"
which = "4"
dirs = "2"
rand = "0.7"

[dev-dependencies]
mockall = "0.7.0"

[dev-dependencies.cargo-husky]
version = "1"
default-features = false
features = ["precommit-hook", "run-cargo-test", "run-cargo-clippy", "run-cargo-fmt"]

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["winuser"] }
sdl2-sys = { git = "https://github.com/uhuntu/rust-sdl2.git", branch = "hunt", default-features = false, features = ["bundled", "static-link"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"
sdl2-sys = { git = "https://github.com/uhuntu/rust-sdl2.git", branch = "hunt", default-features = false, features = ["bundled", "static-link"] }

[profile.release]
debug = false
lto = true
incremental = true
opt-level = 'z'

[package.metadata.bundle]
name = "Neovide"
identifier = "com.kethku.neovide"
icon = ["assets/nvim.ico"]
version = "0.6.0"
resources = []
copyright = "Copyright (c) keith 2020. All rights reserved."
category = "Productivity"
short_description = "A simple GUI for Neovim."
long_description = """
This is a simple graphical user interface for Neovim. Where possible there are some graphical improvements, but it should act functionally like the terminal UI.
"""
